// Stub adapter generated by ai-pipeline in CLAUDE_DISABLED mode.
// Wraps dummyjson.com so the pipeline completes end-to-end without a key.

import type {
  PartSearchAdapter,
  ExecutionContext,
  PartQuery,
  PartResult,
  HealthStatus,
  AvailabilityStatus,
} from '../../shared/interfaces/adapter.types.js';

const BASE_URL = 'https://dummyjson.com';

function mapAvailability(stock: number | undefined): AvailabilityStatus {
  if (stock === undefined) return 'unknown';
  return stock > 0 ? 'in_stock' : 'out_of_stock';
}

const adapter: PartSearchAdapter = {
  adapterId: 'gen-test',
  adapterName: 'AI Gen Test (dummyjson.com)',
  capabilities: {
    mode: 'http',
    needsAuth: false,
    supportsBulkSearch: false,
    maxRPS: 5,
    searchByVIN: false,
    searchByCross: false,
  },
  async initialize(ctx: ExecutionContext): Promise<void> {
    ctx.logger.info('stub: initialize');
  },
  async search(ctx: ExecutionContext, query: PartQuery): Promise<PartResult[]> {
    const q = query.partNumber?.trim();
    if (!q) return [];
    const limit = Math.min(Math.max(query.limit ?? 10, 1), 20);
    const url = BASE_URL + '/products/search?q=' + encodeURIComponent(q) + '&limit=' + limit;
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 8000);
    try {
      const res = await ctx.fetch(url, {
        method: 'GET',
        signal: controller.signal,
        headers: { 'Accept': 'application/json' },
      });
      if (!res.ok) {
        if (res.status === 404) return [];
        throw new Error('stub: upstream HTTP ' + res.status);
      }
      const body = (await res.json()) as {
        products?: Array<{ id: number; title: string; price: number; brand?: string; stock?: number; sku?: string }>;
      };
      const products = body.products ?? [];
      const now = new Date();
      return products.map((p) => ({
        partNumber: String(p.sku ?? p.id),
        brand: p.brand ?? 'unknown',
        name: p.title,
        price: Number.isFinite(p.price) ? p.price : 0,
        currency: 'USD',
        availability: mapAvailability(p.stock),
        ...(p.stock !== undefined ? { quantity: p.stock } : {}),
        source: ctx.siteId,
        sourceUrl: BASE_URL + '/products/' + p.id,
        updatedAt: now,
      }));
    } finally {
      clearTimeout(timer);
    }
  },
  async healthCheck(ctx: ExecutionContext): Promise<HealthStatus> {
    const t0 = Date.now();
    try {
      const res = await ctx.fetch(BASE_URL + '/products/1', { method: 'GET' });
      return { ok: res.ok, latencyMs: Date.now() - t0, checkedAt: new Date() };
    } catch (err) {
      return {
        ok: false,
        latencyMs: Date.now() - t0,
        error: err instanceof Error ? err.message : String(err),
        checkedAt: new Date(),
      };
    }
  },
};

export default adapter;
